Fixes to e2e tests
Signed-off-by: Simon Marechal <bartavelle@gmail.com>

diff --git a/.github/workflows/e2e-compose-tests.yml b/.github/workflows/e2e-compose-tests.yml
--- a/.github/workflows/e2e-compose-tests.yml
+++ b/.github/workflows/e2e-compose-tests.yml
@@ -45,8 +45,28 @@ jobs:
             echo "-- Run e2e tests --"
             pushd e2e
             IP=127.0.0.1
-            python3 test_e2e.py --log-level INFO --base-protected-url http://$IP:30081 --base-conf-url http://$IP:30000/api/v3/ --base-ui-url http://$IP:30080 --elasticsearch-url http://$IP:9200/ --luatests-path ../curiefense/curieproxy/rust/luatests
+            pytest --log-level INFO --base-protected-url http://$IP:30081 --base-conf-url http://$IP:30000/api/v3/ --base-ui-url http://$IP:30080 --elasticsearch-url http://$IP:9200/ --junit-xml pytest.xml --luatests-path ../curiefense/curieproxy/rust/luatests .
             popd
+
+            echo "-- Run bitflip tests tests --"
+            echo "TODO"
+            # Here we are not interested in the e2e tests results, almost all
+            # of which are expected to fail. We just want to ensure envoy does
+            # not crash with malformed requests.
+            # A subset of tests is selected to exercise most code paths; not
+            # all tests are run to avoid spending more than 5 minutes on this
+            # in CI
+            # pushd e2e
+            # ENVOY_PID_BEFORE=$(pgrep envoy)
+            # IP=127.0.0.1
+            # pytest --log-level INFO --base-protected-url http://$IP:30081 --base-conf-url http://$IP:30000/api/v3/ --base-ui-url http://$IP:30080 --elasticsearch-url http://$IP:9200/ --flip-requests . -k 'test_geo or test_ratelimit_scope_include[headers] or test_cookies[active] or test_headers[active] or test_method[active] or test_path[active] or test_query[active] or test_uri[active] or test_nondefault_content_filter_profile_short_headers or test_length_short[cookies] or test_non_allowlisted_value_restrict[ignore_alphanum-headers-regex] or test_content_filter_rule[ignore_alphanum-params-content_filter_rules1] or test_allowlisted_value[no_ignore_alphanum-params-name-norestrict]' || true
+            # ENVOY_PID_AFTER=$(pgrep envoy)
+            # if [ "$ENVOY_PID_BEFORE" != "$ENVOY_PID_AFTER" ]; then
+            #   echo "Error: probable envoy crash during bitflip smoke testing"
+            #   exit 1
+            # fi
+            # popd
+
 
       - name: Dump compose logs
         if: ${{ failure() }}
@@ -55,3 +75,28 @@ jobs:
             # purposes.
             pushd deploy/compose
             docker-compose logs
+
+      - name: Publish Unit Test Results
+        # TODO implement https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories
+        uses: EnricoMi/publish-unit-test-result-action@ea8720de4a2e723f8204d44fc0178744cf401c1a
+        with:
+          files: e2e/pytest.xml
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          check_name: E2E Test Results on docker-compose
+          comment_title: E2E Test Statistics
+          hide_comments: all but latest
+          comment_on_pr: true
+          report_individual_runs: true
+          deduplicate_classes_by_file_name: false
+        if: >
+          always() &&
+          github.event.sender.login != 'dependabot[bot]' &&
+          ( github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository )
+
+      - name: Upload Test Results
+        if: always()
+        uses: actions/upload-artifact@v2
+        with:
+          name: Unit Test Results
+          path: |
+            e2e/pytest.xml
